export const medium : string[] = [
  "abandon", "ability", "airport", "absolute", "academic", "accept", "accident", "account", "accurate", "active", "actual",
  "address", "advance", "advice", "afraid", "agency", "agenda", "agreement", "amount", "animal", "answer",
  "appear", "approach", "arrange", "article", "artist", "aspect", "attack", "attempt", "attend", "author",
  "average", "avoid", "balance", "battle", "beauty", "belief", "belong", "benefit", "beyond", "border",
  "bottle", "bottom", "boundary", "branch", "breath", "bridge", "broken", "budget", "building", "burden",
  "button", "cabinet", "camera", "campus", "cancel", "cancer", "candle", "canvas", "capacity", "capital",
  "captain", "capture", "career", "careful", "carrier", "castle", "casual", "cattle", "caught", "center",
  "central", "century", "certain", "chamber", "chance", "change", "channel", "chapter", "charge", "charity",
  "charter", "cheese", "choice", "choose", "circle", "citizen", "classic", "climate", "closest", "clothes",
  "coastal", "collect", "college", "column", "combat", "combine", "comfort", "command", "comment", "common",
  "company", "compare", "compass", "complex", "concept", "concern", "concert", "conduct", "connect", "consist",
  "contact", "contain", "content", "contest", "context", "control", "convert", "correct", "council", "counsel",
  "counter", "courage", "course", "crystal", "culture", "current", "custom", "damage", "danger", "darker",
  "debate", "decade", "decide", "declare", "decline", "default", "defend", "degree", "deliver", "demand",
  "density", "depend", "deposit", "deserve", "design", "desire", "detail", "detect", "device", "devote",
  "diamond", "differ", "digital", "dignity", "direct", "disease", "display", "distant", "divide", "doctor",
  "double", "driver", "easily", "effect", "effort", "either", "element", "emerge", "empire", "employ",
  "empty", "enable", "energy", "engine", "enough", "ensure", "entire", "escape", "estate", "ethnic",
  "exceed", "except", "expand", "expect", "expert", "export", "extend", "extent", "fabric", "factor",
  "failed", "fairly", "famous", "father", "feature", "fellow", "female", "figure", "finger", "finish",
  "flight", "flower", "follow", "forest", "forget", "formal", "format", "former", "fourth", "friend",
  "frozen", "future", "gallery", "garden", "gather", "gender", "general", "genius", "gentle", "global",
  "golden", "ground", "growth", "guilty", "habitat", "handle", "happen", "hardly", "health", "hearing",
  "heaven", "heavily", "helpful", "hidden", "highly", "history", "hollow", "honest", "horror", "hunger",
  "ignore", "impact", "import", "impose", "impress", "improve", "include", "income", "index", "inform",
  "initial", "injury", "inside", "insist", "install", "instance", "intend", "invent", "invest", "invite",
  "island", "issue", "itself", "jacket", "journey", "justice", "justify", "keeper", "kidney", "kitchen",
  "ladder", "laptop", "larger", "latest", "lawyer", "leader", "league", "legacy", "legend", "lesson",
  "letter", "level", "likely", "limit", "liquid", "listen", "living", "locate", "logical", "machine",
  "mainly", "manage", "manner", "manual", "margin", "marker", "market", "master", "hyena","tortoise",
  "antelope","chimpanzee","gorilla","porcupine","ostrich","python","crocodile","hippopotamus",
  "rhinoceros","giraffe","zebra","squirrel","pigeon","parrot","owl","vulture","termite","centipede",
  "millipede","scorpion","mongoose","jackal","baboon","pangolin","chameleon","stork","gazelle", "matter", "mature",
  
  // 300 New Words Added Below
  "absorb", "accent", "access", "accord", "action", "adjust", "afford", "almost", "always", "anchor",
  "annual", "appeal", "arrest", "arrive", "assist", "assume", "assure", "attach", "autumn", "avenue",
  "backup", "banner", "barely", "barrel", "basket", "beacon", "behalf", "behave", "behind", "beside",
  "better", "bitter", "bounce", "breeze", "bright", "bronze", "browse", "bubble", "bucket", "bullet",
  "butter", "bypass", "cabin", "cable", "canopy", "canyon", "carbon", "carpet", "carrot", "carton",
  "casino", "cavern", "celery", "cellar", "cement", "cereal", "cherry", "chosen", "church", "cinema",
  "circus", "clause", "clever", "client", "clinic", "closed", "closet", "cloudy", "clutch", "coffee",
  "collar", "comedy", "commit", "compel", "comply", "concur", "confer", "cookie", "corner", "corpus",
  "costly", "cotton", "county", "couple", "coupon", "cousin", "covert", "cradle", "crater", "craven",
  "credit", "crease", "create", "crisis", "critic", "cruise", "crunch", "cuckoo", "curfew", "dagger",
  "dainty", "dancer", "daring", "darken", "dating", "dealer", "deeply", "defeat", "defect", "define",
  "delete", "depart", "depict", "deploy", "derive", "desert", "detach", "detain", "devour", "dialog",
  "digest", "dinner", "disarm", "discus", "dismal", "dismay", "diving", "domain", "donate", "donkey",
  "doodle", "dosage", "dotage", "dragon", "drawer", "dreamy", "drench", "driven", "drowsy", "during",
  "dynamo", "eager", "earned", "earthy", "easter", "eclipse", "eldest", "eleven", "embark", "emblem",
  "embody", "empress", "enamel", "ending", "endure", "engage", "enigma", "enlist", "enmity", "enroll",
  "entail", "entity", "envied", "equity", "eraser", "errand", "escort", "esteem", "ethics", "evaded",
  "evenly", "evince", "evolve", "excess", "excise", "excuse", "exempt", "exhort", "exodus", "exotic",
  "expose", "extant", "facade", "facing", "fading", "falcon", "fallen", "falser", "family", "famine",
  "famish", "farmer", "fasten", "faucet", "feline", "fencer", "fennel", "ferret", "fervor", "fescue",
  "festal", "fibber", "fickle", "fields", "fierce", "fiesta", "fifths", "finder", "firmly", "fiscal",
  "fishes", "flavor", "flecks", "fleece", "fleshy", "flimsy", "floors", "floral", "fluted", "flying",
  "folder", "forage", "forbid", "forces", "forgot", "fossil", "foster", "fought", "freeze", "frenzy",
  "fresco", "friars", "fright", "fringe", "frolic", "fronts", "fruits", "fryers", "fumble", "fungus",
  "funnel", "fusion", "gadget", "gainer", "galaxy", "gallon", "gallop", "gamble", "gander", "garble",
  "gargle", "garlic", "garnet", "garter", "gashes", "gating", "gauche", "gauges", "gavels", "gazing",
  "geckos", "geisha", "genial", "govern", "gentry", "gerbil", "geyser", "ghosts", "giants", "gibbon",
  "giggle", "ginger", "glades", "glance", "glands", "glared", "glares", "glassy", "glazed", "glazes",
  "gleams", "gleans", "glides", "glider", "gloats", "globes", "gloomy", "glossy", "gloves", "glowed",
  "glints", "hacker", "haggis", "hailed", "hallow", "halter", "halves", "hamlet", "hamper", "harbor"
];

export const easy : string[] = [
  "apple", "baby", "back", "ball", "bear", "bed", "bell", "bird", "boat", "box",
  "boy", "bread", "brother", "cake", "car", "cat", "chair", "chicken", "child", "coat",
  "corn", "cow", "day", "dog", "doll", "door", "duck", "egg", "eye", "farm",
  "farmer", "father", "feet", "fire", "fish", "floor", "flower", "game", "garden", "girl",
  "good", "grass", "ground", "hand", "head", "hill", "home", "horse", "house", "kitty",
  "leg", "letter", "man", "men", "milk", "money", "morning", "mother", "name", "nest",
  "night", "paper", "party", "picture", "pig", "rabbit", "rain", "ring", "robin", "school",
  "seed", "sheep", "shoe", "sister", "snow", "song", "squirrel", "stick", "street", "sun",
  "table", "thing", "time", "top", "toy", "tree", "watch", "water", "way", "wind",
  "window", "wood", "about", "better", "bring", "carry", "clean", "cut", "done", "draw",
  "drink", "eight", "fall", "far", "full", "got", "grow", "hold", "hot", "hurt",
  "if", "keep", "kind", "laugh", "light", "long", "much", "myself", "never", "only",
  "own", "pick", "seven", "shall", "show", "six", "small", "start", "ten", "today",
  "together", "try", "warm", "always", "around", "because", "been", "before", "best", "both",
  "buy", "call", "cold", "does", "fast", "first", "five", "found", "gave", "goes",
  "green", "its", "made", "many", "off", "or", "pull", "read", "right", "sing",
  "sit", "sleep", "tell", "their", "these", "those", "upon", "us", "use", "very",
  "wash", "which", "why", "wish", "work", "would", "write", "your", "after", "again",
  "an", "any", "as", "ask", "by", "could", "every", "fly", "from", "give",
  "going", "had", "has", "her", "him", "his", "how", "just", "know", "let",
  "live", "may", "of", "old", "once", "open", "over", "put", "round", "some",
  "stop", "take", "thank", "them", "then", "think", "walk", "were", "when", "all",
  "am", "are", "at", "ate", "be", "black", "brown", "but", "came", "did",
  "do", "eat", "four", "get", "have", "he", "into", "like", "must", "new",
  "no", "now", "on", "our", "out", "please", "pretty", "ran", "ride", "saw",
  "say", "she", "so", "soon", "that", "there", "they", "this", "too", "under",
  "want", "was", "well", "went", "what", "white", "who", "will", "with", "yes",
  "big", "blue", "can", "come", "down", "find", "for", "funny", "go", "help",
  "here", "in", "is", "it", "jump", "little", "look", "make", "me", "my",
  "not", "one", "play", "red", "run", "said", "see", "the", "up", "where", "goat", 'cow',
  'pig', 'elephant', 'catfish', 'ant', 'mosquito', 'butterfly', 'sheep', 'ram', 'camel',
  'dog', 'cat', 'eagle',"chicken", "turkey", "duck", "horse", "donkey", "monkey", "rat",
  "bat", "snake", "lizard", "toad", "frog", "snail", "spider", "fly", "bee", "fish", 
  "crab", "grasshopper", "cockroach",

  // 300 New Easy Words Added Below
  "act", "add", "age", "air", "arm", "art", "ash", "bad", "bag", "bar",
  "bat", "bee", "beg", "bet", "bit", "bug", "bus", "cab", "cap", "cop",
  "cot", "cry", "cub", "cup", "dad", "den", "dig", "dim", "dip", "dot",
  "dry", "ear", "elf", "elk", "elm", "end", "fan", "fat", "fax", "fee",
  "fig", "fin", "fit", "fog", "fox", "fry", "fun", "gap", "gas", "gem",
  "gig", "gum", "gun", "gut", "gym", "ham", "hat", "hay", "hen", "hid",
  "hip", "hit", "hog", "hop", "hug", "hum", "hut", "ice", "ill", "ink",
  "inn", "jam", "jar", "jaw", "jet", "job", "jog", "joy", "jug", "jut",
  "keg", "key", "kid", "kin", "kit", "lab", "lag", "lap", "law", "lay",
  "lid", "lip", "log", "lot", "mad", "map", "mat", "met", "mix", "mob",
  "mom", "mop", "mud", "mug", "nap", "net", "nod", "nut", "oak", "oat",
  "odd", "oil", "owl", "pad", "pal", "pan", "paw", "pay", "peg", "pen",
  "pet", "pie", "pin", "pit", "pod", "pop", "pot", "pub", "pug", "pup",
  "rag", "raw", "ray", "rib", "rim", "rip", "rod", "rot", "row", "rub",
  "rug", "rum", "rut", "sad", "sap", "sea", "set", "sew", "sin", "sip",
  "sir", "ski", "sky", "sob", "son", "sow", "spy", "sub", "sum", "tab",
  "tag", "tan", "tap", "tar", "tax", "tea", "tie", "tin", "tip", "toe",
  "tow", "tub", "tug", "van", "vat", "vet", "vow", "wag", "war", "wax",
  "web", "wet", "wig", "win", "wok", "won", "wow", "yak", "yam", "yap",
  "yip", "yum", "zag", "zip", "zoo", "bake", "bare", "bark", "base", "beak",
  "bean", "beat", "beef", "beep", "belt", "bend", "bike", "bite", "blow", "body",
  "bone", "book", "boot", "boss", "bowl", "bump", "burn", "bush", "busy", "camp",
  "card", "care", "cash", "cave", "chat", "chew", "chin", "chip", "chop", "clam",
  "clap", "claw", "clay", "club", "clue", "coal", "coin", "cook", "cool", "copy",
  "cord", "core", "cork", "cost", "crew", "crop", "crow", "cube", "cure", "cute",
  "damp", "dark", "dart", "dash", "date", "dawn", "deaf", "deal", "dear", "deck",
  "deep", "deer", "desk", "dial", "dice", "diet", "dirt", "dish", "dive", "dock",
  "dome", "dose", "drag", "drop", "drum", "dual", "dust", "duty", "each", "earn",
  "east", "easy", "edge", "epic", "even", "evil", "exam", "exit", "face", "fact",
  "fade", "fail", "fake", "fame", "fang", "fare", "fear", "feed", "feel", "file"
];

export const hard : string[] = [
  "aberration", "abstruse", "accolade", "acerbic", "acrimony", "acumen", 'hedgehog',  "adamant", "adroit", "adulation", "aegis",
  "aesthetic", "affable", "alacrity", "alleviate", "amalgamate", "ambiguous", "ambivalence", "ameliorate", "anachronism", "anathema",
  "animosity", "anomaly", "antediluvian", "antipathy", "antiquated", "apathy", "apocryphal", "appease", "apprehension", "arcane",
  "archaic", "arduous", "articulate", "ascetic", "asperity", "assuage", "astute", "attenuate", "audacious", "augment",
  "auspicious", "austere", "avarice", "banal", "bellicose", "belligerent", "benevolent", "benign", "blandishment", "blatant",
  "bolster", "bombastic", "boorish", "bucolic", "burgeon", "cacophony", "cajole", "calumny", "camaraderie", "candid",
  "capricious", "captious", "castigate", "catalyst", "cathartic", "caustic", "censure", "charlatan", "chicanery", "choleric",
  "circumlocution", "circumspect", "clandestine", "clemency", "cloying", "coalesce", "cogent", "cognizant", "coherent", "collusion",
  "commensurate", "compelling", "complacent", "compliant", "comprehensive", "conciliatory", "concise", "condescend", "condone", "conflagration",
  "conflate", "confound", "congenial", "conjecture", "consensus", "consummate", "contentious", "contrite", "contumacious", "conundrum",
  "convoluted", "copious", "corroborate", "cosmopolitan", "covert", "credulous", "cryptic", "culpable", "cumbersome", "cursory",
  "cynical", "dearth", "debacle", "debilitate", "decorum", "defame", "deference", "deleterious", "delineate", "demagogue",
  "demur", "denigrate", "deprecate", "deride", "derivative", "desiccate", "despot", "desultory", "diaphanous", "diatribe",
  "didactic", "diffident", "digression", "dilatory", "dilettante", "dirge", "discern", "discordant", "discrepancy", "discursive",
  "disdain", "disingenuous", "disparage", "disparate", "dissemble", "disseminate", "dissonance", "divergent", "dogmatic", "dormant",
  "draconian", "ebullient", "eclectic", "efficacy", "effrontery", "egalitarian", "egregious", "elegy", "elicit", "eloquent",
  "elucidate", "embellish", "empirical", "emulate", "enervate", "engender", "enigma", "ennui", "ephemeral", "epic",
  "equanimity", "equivocal", "erudite", "esoteric", "eulogy", "euphemism", "evanescent", "exacerbate", "exalt", "exculpate",
  "execrable", "exhort", "exigent", "exonerate", "exorbitant", "expedient", "expedite", "explicit", "expunge", "extemporaneous",
  "extol", "extraneous", "extrapolate", "extricate", "facetious", "fallacious", "fastidious", "fatuous", "fawning", "felicitous",
  "fervent", "fickle", "fidelity", "flagrant", "flippant", "flout", "foment", "forestall", "fortuitous", "fractious",
  "frivolous", "frugal", "fulminate", "furtive", "futile", "gainsay", "garrulous", "gauche", "germane", "glib",
  "gossamer", "grandiloquent", "gregarious", "guile", "hackneyed", "halcyon", "hallowed", "hapless", "harangue", "hegemony",
  "heretical", "hermetic", "heterodox", "hierarchy", "hinder", "histrionic", "homogeneous", "hubris", "hyperbole", "iconoclast",
  "idiosyncrasy", "ignominious", "illicit", "immutable", "impartial", "impeccable", "impediment", "imperturbable", "impetuous", "implacable",
  "implicit", "impudence", "inadvertent", "inane", "incessant", "inchoate", "incisive", "incongruous", "incorrigible", "indefatigable",
  "indigenous", "indigent", "indolent", "indomitable", "ineffable", "inept", "inexorable", "infamous", "ingenious", "ingenuous",
  "inimical", "iniquity", "innocuous", "insidious", "insipid", "insolent", "intransigent", "intrepid", "inundate", "inured",
  "invective", "inveterate", "irascible", "irresolute", "itinerary", "jeopardize", "jocular", "judicious", "juxtapose", "kinetic",
  "laconic", "lament", "languid", "latent", "aardvark","albatross","armadillo","axolotl","binturong",
  "bushbaby","capybara","caracal","cassowary","chinchilla","coelacanth","dugong","echidna","fossa",
  "gharial","kakapo","kinkajou","macaque","narwhal","ocelot","okapi","orangutan","platypus","ptarmigan",
  "quetzal","salamander","serval","tapir","tuatara","wildebeest", "laudatory", "lethargic", "lionize", 
  "loquacious", "lucid","lugubrious",
];

export const mediumHard : string[] = [
  // Original "Medium-Hard" / Upper-Intermediate list
  "abolish", "abrupt", "abundant", "accessible", "accommodate", "accumulate", "acknowledge", "acquire", "adequate", "adjacent",
  "adolescent", "advocate", "aggregate", "aggressive", "allocate", "alternative", "amateur", "amend", "analyze", "anticipate",
  "apparent", "appreciate", "arbitrary", "arrogant", "assemble", "assess", "associate", "astonish", "authentic", "beneficial",
  "betray", "bewilder", "bias", "boycott", "brilliant", "calculate", "campaign", "candidate", "capability", "category",
  "caution", "chronological", "circulate", "civilian", "clarify", "coincide", "collapse", "colleague", "commence", "commission",
  "commit", "commodity", "communicate", "compatible", "compel", "compensate", "compile", "complicate", "comply", "component",
  "comprehend", "compromise", "conceal", "concede", "conceive", "concentrate", "conclude", "concrete", "condemn", "condense",
  "confer", "confess", "confide", "confirm", "confiscate", "conflict", "conform", "confront", "confuse", "congregate",
  "consequence", "conservative", "conserve", "consistent", "constant", "constitute", "constrain", "construct", "consume", "contaminate",
  "contemporary", "continuous", "contradict", "contribute", "controversy", "convenient", "conventional", "coordinate", "correlate", "correspond",
  "crucial", "currency", "cylinder", "debris", "declaration", "dedicate", "deduce", "deficient", "deliberate", "demolish",
  "demonstrate", "denounce", "deplete", "descend", "desperate", "deteriorate", "determine", "devastate", "diagnose", "dictate",
  "diminish", "disaster", "discard", "discharge", "discipline", "disclose", "disconnect", "discriminate", "disguise", "dismantle",
  "dismiss", "dispatch", "disperse", "dispose", "dispute", "disrupt", "dissolve", "distinct", "distinguish", "distribute",
  "diverse", "document", "dominate", "drastic", "duration", "economy", "elaborate", "elevate", "eliminate", "elude",
  "embarrass", "emphasis", "encounter", "endeavor", "endure", "enforce", "enormous", "enterprise", "entertain", "enthusiasm",
  "equivalent", "erupt", "establish", "estimate", "evaluate", "evidence", "exaggerate", "examine", "exception", "exchange",
  "exclaim", "exclude", "execute", "exhaust", "exhibit", "expand", "expedition", "experiment", "explode", "exploit",
  "explore", "external", "extinct", "extract", "extraordinary", "extreme", "facilitate", "fascinate", "fatigue", "feasible",
  "fluctuate", "frustrate", "fundamental", "furious", "genuine", "guarantee", "hypothesis", "illuminate", "illustrate", "implement",
  "implication", "incentive", "incorporate", "inevitable", "innovate", "integrate", "interfere", "interpret", "intervene", "intimidate",
  "intricate", "intuition", "isolate", "justify", "legitimate", "manipulate", "marvelous", "mechanism", "mediate", "metaphor",
  "negotiate", "notorious", "obstacle", "prominent", "protocol", "provoke", "reluctant", "scrutinize", "skeptical", "spontaneous",
  "subsequent", "substitute", "suppress", "tangible", "tolerate", "unanimous", "undermine", "validate", "versatile", "vibrant",
  "vindicate", "vulnerable", "alpaca", "badger", "beaver", "bison", "cheetah", "cougar", "coyote", "dingo",
  "ferret", "flamingo", "iguana", "jaguar", "koala", "lemur", "leopard", "llama", "manatee", "marmot",
  "meerkat", "moose", "otter", "panda", "panther", "pelican", "penguin", "raccoon", "reindeer", "seal",
  "skunk", "sloth", "toucan", "walrus", "weasel", "wombat",
  
  // 300 New "Medium-Hard" / Upper-Intermediate Additions
  "abandonment", "abbreviation", "abdicate", "abduction", "abstinence", "abstraction", "absurdity", "acceleration", "accessory", "acclaim",
  "acclimate", "accomplishment", "accordance", "accountability", "accuracy", "accusation", "accustom", "achievement", "acquisition", "acquittal",
  "activation", "adaptation", "addictive", "addition", "adherence", "adjustment", "administer", "admiration", "admission", "adoption",
  "adornment", "adrenaline", "advancement", "advantageous", "adversary", "adverse", "advisory", "advocacy", "affectionate", "affiliation",
  "affirmation", "affliction", "affluent", "aftermath", "agenda", "aggravate", "aggregation", "agility", "agitation", "agony",
  "agrarian", "airborne", "alias", "alienation", "alignment", "allegation", "allegiance", "alleviation", "allocation", "allotment",
  "allowance", "allusion", "alteration", "alternate", "altitude", "altruistic", "amateurish", "ambassador", "ambition", "amendment",
  "amiable", "amicable", "ammunition", "amortization", "amphibian", "amplification", "amplitude", "amusement", "analogy", "analytical",
  "anatomy", "ancestor", "ancestry", "anecdote", "angular", "animation", "annexation", "annihilate", "annotation", "announcement",
  "annoyance", "antagonist", "antecedent", "antedate", "anterior", "anthology", "anticipation", "antidote", "antisocial", "antithesis",
  "anxiety", "apathetic", "aperture", "apologetic", "apparatus", "apparel", "apparition", "appeasement", "appellate", "appendix",
  "appetite", "appetizer", "applicable", "application", "appraisal", "appreciable", "apprehend", "apprehensive", "apprentice", "approach",
  "appropriate", "appropriation", "approval", "approximate", "aptitude", "aquarium", "aquatic", "architecture", "archive", "ardent",
  "argumentation", "arid", "arithmetic", "arousal", "arrangement", "arrogance", "arsenal", "artery", "artificial", "artillery",
  "ascertain", "aspiration", "assassinate", "assault", "assertion", "assertive", "assessment", "assignment", "assimilate", "assistance",
  "assumption", "assurance", "asteroid", "astonishment", "astray", "astrology", "astronaut", "astronomy", "asymmetrical", "athletic",
  "atmosphere", "atrocity", "attachment", "attainment", "attendance", "attentive", "attribute", "atypical", "auction", "audacious",
  "auditory", "authenticate", "authoritarian", "authoritative", "authority", "authorization", "automate", "automatic", "automaton", "autonomous",
  "autonomy", "auxiliary", "avalanche", "avenge", "avenue", "aversion", "aviation", "avoidance", "awakening", "awareness",
  "backdrop", "background", "backward", "bacteria", "baffling", "baggage", "bailout", "beset", "balcony", "ballast",
  "balloon", "ballot", "bamboo", "bandage", "bankrupt", "bankruptcy", "banquet", "banter", "baptism", "barbarian",
  "barbaric", "barbecue", "barometer", "barricade", "barrier", "barter", "bashful", "basics", "basin", "basis",
  "battalion", "batter", "battery", "bearing", "beastly", "besiege", "beforehand", "behavioral", "behemoth", "belated",
  "belief", "believable", "belittle", "benchmark", "beneath", "benefactor", "beneficiary", "benevolence", "bequest", "bereaved",
  "beseech", "bestow", "betoken", "beverage", "bicameral", "bicker", "biennial", "bilateral", "bilingual", "billionaire",
  "binoculars", "biography", "biological", "biopsy", "biosphere", "biped", "birthright", "biscuit", "bisect", "bizarre",
  "blackmail", "blacksmith", "bovine", "bland", "blasphemy", "blemish", "blizzard", "blockade", "blockage", "blueprint",
  "blunder", "blunt", "blur", "bluster", "boast", "bodyguard", "boisterous", "boldness", "bravado", "bombardment",
  "bondage", "brevity", "boon", "boost", "boredom", "borough", "botanical", "botany", "boulder", "boulevard",
  "breakthrough", "brink", "breach", "bouquet", "boutique", "braille", "brace", "bracelet", "bracket", "bewitch"
];

export const animals : string[] = [
  "dog", "cat", "cow", "pig", "sheep", "horse", "goat", "chicken", "duck", "turkey",
  "goose", "donkey", "mule", "rabbit", "guinea pig", "hamster", "gerbil", "mouse", "rat", "ferret",
  "lion", "tiger", "elephant", "giraffe", "zebra", "hippopotamus", "rhinoceros", "cheetah", "leopard", "hyena",
  "wildebeest", "gazelle", "antelope", "baboon", "chimpanzee", "gorilla", "ostrich", "meerkat", "warthog", "jackal",
  "lemur", "aardvark", "pangolin", "mongoose", "buffalo", "impala", "kudu", "springbok", "dikdik", "okapi",
  "bear", "wolf", "coyote", "fox", "deer", "moose", "elk", "caribou", "bison", "raccoon",
  "skunk", "opossum", "porcupine", "beaver", "squirrel", "chipmunk", "groundhog", "cougar", "jaguar", "sloth",
  "armadillo", "anteater", "llama", "alpaca", "vicuna", "capybara", "chinchilla", "tapir", "peccary", "coati",
  "panda", "orangutan", "macaque", "gibbon", "camel", "yak", "kangaroo", "koala", "wallaby", "wombat",
  "platypus", "echidna", "tasmanian devil", "dingo", "kiwi", "cassowary", "emu", "kookaburra", "eagle", "hawk",
  "falcon", "owl", "parrot", "pigeon", "dove", "crow", "raven", "jay", "robin", "sparrow",
  "finch", "woodpecker", "pelican", "seagull", "albatross", "penguin", "swan", "flamingo", "stork", "heron",
  "crane", "peacock", "pheasant", "quail", "toucan", "macaw", "hummingbird", "kingfisher", "snake", "lizard",
  "turtle", "tortoise", "crocodile", "alligator", "iguana", "chameleon", "gecko", "skink", "monitor", "komodo",
  "python", "boa", "cobra", "viper", "frog", "toad", "salamander", "newt", "axolotl", "caecilian",
  "chuckwalla", "anole", "basilisk", "terrapin", "gharial", "mamba", "adder", "whale", "dolphin", "porpoise",
  "shark", "stingray", "manta", "octopus", "squid", "cuttlefish", "jellyfish", "starfish", "seahorse", "manatee",
  "dugong", "walrus", "seal", "sea lion", "otter", "crab", "lobster", "shrimp", "krill", "barnacle",
  "clam", "oyster", "mussel", "scallop", "snail", "slug", "urchin", "salmon", "tuna", "trout",
  "bass", "cod", "snapper", "grouper", "halibut", "flounder", "catfish", "carp", "goldfish", "koi",
  "guppy", "betta", "piranha", "eel", "barracuda", "marlin", "swordfish", "sailfish", "clownfish", "angelfish",
  "pufferfish", "lionfish", "sturgeon", "tarpon", "tilapia", "herring", "sardine", "ant", "bee", "wasp",
  "hornet", "butterfly", "moth", "fly", "mosquito", "beetle", "ladybug", "firefly", "grasshopper", "cricket",
  "locust", "mantis", "cockroach", "termite", "dragonfly", "damselfly", "flea", "tick", "spider", "tarantula",
  "scorpion", "centipede", "millipede", "worm", "leech", "cicada", "aphid", "badger", "wolverine", "mink",
  "marten", "stoat", "weasel", "polecat", "fisher", "binturong", "civet", "genet", "fossa", "caracal",
  "serval", "ocelot", "lynx", "bobcat", "puma", "panther", "hedgehog", "mole", "shrew", "vole",
  "lemming", "pika", "prairie dog", "marmot", "hyrax", "tenrec", "bandicoot", "quokka", "tarsier", "loris",
  "galago", "aye-aye", "capuchin", "marmoset", "tamarin", "howler", "mandrill", "colobus", "langur", "saki",
  "uakari", "titi", "indri", "sifaka", "narwhal", "beluga", "orca", "sponge", "coral", "anemone"
];


export const scientific : string[] = [
  "cell", "membrane", "nucleus", "cytoplasm", "organelle", "mitochondria", "ribosome", "chloroplast", "vacuole", "tissue",
  "organ", "system", "organism", "species", "population", "community", "ecosystem", "biosphere", "ecology", "habitat",
  "niche", "biome", "food", "chain", "web", "producer", "consumer", "decomposer", "herbivore", "carnivore",
  "omnivore", "predator", "prey", "parasite", "host", "symbiosis", "mutualism", "commensalism", "evolution", "natural",
  "selection", "mutation", "genetics", "gene", "dna", "rna", "chromosome", "trait", "heredity", "allele",
  "dominant", "recessive", "genotype", "phenotype", "reproduction", "sexual", "asexual", "mitosis", "meiosis", "clone",
  "fertilization", "zygote", "embryo", "fetus", "plant", "animal", "fungus", "protist", "bacteria", "virus",
  "root", "stem", "leaf", "flower", "fruit", "seed", "pollen", "nectar", "photosynthesis", "respiration",
  "transpiration", "stoma", "xylem", "phloem", "anatomy", "physiology", "skeleton", "bone", "muscle", "joint",
  "cartilage", "ligament", "tendon", "skin", "hair", "nail", "brain", "nerve", "neuron", "spinal",
  "cord", "sense", "eye", "ear", "nose", "tongue", "heart", "blood", "vessel", "artery",
  "vein", "capillary", "plasma", "platelet", "lung", "trachea", "bronchi", "alveoli", "breathe", "oxygen",
  "carbon", "dioxide", "stomach", "intestine", "liver", "pancreas", "kidney", "bladder", "urine", "hormone",
  "gland", "endocrine", "immune", "antibody", "antigen", "disease", "infection", "pathogen", "allergy", "vaccine",
  "medicine", "drug", "dose", "taxonomy", "kingdom", "phylum", "class", "order", "family", "genus",
  "binomial", "nomenclature", "botany", "zoology", "microbe", "flora", "fauna", "protein", "lipid", "carbohydrate",
  "enzyme", "catalyst", "metabolism", "homeostasis", "stimulus", "response", "adaptation", "camouflage", "mimicry", "migration",
  "hibernation", "instinct", "behavior", "fermentation", "chlorophyll", "petal", "sepal", "stamen", "pistil", "ovary",
  "ovule", "germination", "pollination", "cotyledon", "monocot", "dicot", "vascular", "nonvascular", "gymnosperm", "angiosperm",
  "spore", "hyphae", "mycelium", "lichen", "plankton", "phytoplankton", "zooplankton", "benthic", "pelagic", "nekton",
  "atom", "molecule", "element", "compound", "mixture", "solution", "solvent", "solute", "bond", "ionic",
  "covalent", "metallic", "reaction", "reactant", "product", "yield", "acid", "base", "alkali", "salt",
  "neutralization", "oxidation", "reduction", "redox", "combustion", "synthesis", "decomposition", "isotope", "ion", "cation",
  "anion", "proton", "neutron", "electron", "orbital", "shell", "valence", "periodic", "table", "group",
  "period", "metal", "nonmetal", "metalloid", "halogen", "noble", "gas", "organic", "inorganic", "hydrogen",
  "nitrogen", "polymer", "monomer", "plastic", "crystal", "lattice", "alloy", "distillation", "filtration", "chromatography",
  "titration", "concentration", "dilute", "saturated", "supersaturated", "precipitate", "buffer", "activation", "energy", "entropy",
  "enthalpy", "exothermic", "endothermic", "equilibrium", "constant", "rate", "mechanism", "isomer", "structural", "stereo",
  "mole", "avogadro", "stoichiometry", "formula", "mass", "molarity", "molality", "volatile", "sublime", "deposit",
  "amorphous", "pure", "substance", "test", "tube", "beaker", "flask", "pipette", "burette", "cylinder",
  "force", "weight", "power", "work", "speed", "velocity", "acceleration", "momentum", "inertia", "gravity",
  "friction", "tension", "pressure", "volume", "density", "area", "length", "time", "heat", "temperature",
  "thermal", "thermodynamics", "conduction", "convection", "radiation", "wave", "frequency", "amplitude", "wavelength", "sound",
  "pitch", "echo", "light", "reflection", "refraction", "diffraction", "lens", "mirror", "optics", "prism",
  "spectrum", "color", "electricity", "charge", "current", "voltage", "resistance", "circuit", "battery", "wire",
  "magnet", "pole", "field", "induction", "quantum", "photon", "relativity", "kinetic", "potential", "scalar",
  "vector", "mechanics", "fluid", "buoyancy", "vacuum", "laser", "phase", "state", "solid", "liquid",
  "melt", "freeze", "boil", "condense", "evaporate", "sublimate", "dynamics", "statics", "torque", "lever",
  "pulley", "gear", "motor", "engine", "spring", "elastic", "stress", "strain", "fracture", "viscosity",
  "acoustic", "ultrasonic", "ultraviolet", "infrared", "emission", "absorption", "transmission", "transparent", "opaque", "translucent",
  "earth", "crust", "mantle", "core", "lithosphere", "asthenosphere", "tectonic", "plate", "boundary", "fault",
  "fold", "earthquake", "seismic", "epicenter", "magnitude", "volcano", "magma", "lava", "eruption", "vent",
  "crater", "ash", "rock", "igneous", "sedimentary", "metamorphic", "mineral", "cleavage", "hardness", "streak",
  "luster", "weathering", "erosion", "deposition", "sediment", "soil", "sand", "silt", "clay", "humus",
  "horizon", "profile", "fossil", "index", "geologic", "era", "epoch", "cycle", "ocean", "sea",
  "lake", "river", "stream", "ground", "water", "aquifer", "salinity", "tide", "atmosphere", "troposphere",
  "stratosphere", "mesosphere", "thermosphere", "exosphere", "ozone", "layer", "weather", "climate", "meteorology", "barometer",
  "wind", "anemometer", "humidity", "psychrometer", "cloud", "cumulus", "stratus", "cirrus", "precipitation", "rain",
  "snow", "sleet", "hail", "storm", "hurricane", "tornado", "cyclone", "typhoon", "front", "stationary",
  "occluded", "forecasting", "radar", "satellite", "latitude", "longitude", "equator", "prime", "meridian", "hemisphere",
  "axis", "rotation", "revolution", "season", "solstice", "equinox", "glacier", "ice", "sheet", "iceberg",
  "avalanche", "landslide", "tsunami", "continent", "island", "mountain", "valley", "plain", "plateau", "canyon",
  "desert", "forest", "rainforest", "tundra", "taiga", "grassland", "savanna", "space", "universe", "galaxy",
  "milky", "way", "solar", "star", "sun", "planet", "mercury", "venus", "mars", "jupiter",
  "saturn", "uranus", "neptune", "pluto", "dwarf", "moon", "lunar", "orbit", "eclipse", "new",
  "full", "crescent", "gibbous", "waxing", "waning", "asteroid", "belt", "comet", "meteor", "meteoroid",
  "meteorite", "constellation", "zodiac", "telescope", "observatory", "probe", "rover", "station", "astronaut", "cosmos",
  "parsec", "astronomical", "unit", "microgravity", "black", "hole", "singularity", "event", "supernova", "nebula",
  "pulsar", "quasar", "giant", "main", "sequence", "fusion", "fission", "dark", "matter", "bang",
  "expansion", "redshift", "blueshift", "stellar", "cosmic", "ray", "debris", "launch", "rocket",
  "thrust", "payload", "escape", "apogee", "perigee", "perihelion", "aphelion", "research", "hypothesis", "theory",
  "law", "experiment", "variable", "control", "independent", "dependent", "data", "analysis", "conclusion", "observation",
  "inference", "qualitative", "quantitative", "metric", "measure", "calibrate", "laboratory", "microscope", "magnification", "resolution",
  "safety", "goggles", "apron", "gloves", "fume", "hood", "bunsen", "burner", "tongs", "forceps",
  "scalpel", "petri", "dish", "agar", "incubator", "centrifuge", "spectrophotometer", "electrophoresis", "pipet", "syringe",
  "slide", "coverslip", "cuvette", "magnetism", "diamagnetic", "paramagnetic", "ferromagnetic", "superconductor", "semiconductor", "diode",
  "transistor", "capacitor", "resistor", "inductor", "transformer", "amplifier", "oscillator", "rectifier", "inverter", "logic",
  "gate", "microprocessor", "algorithm", "computation", "simulation", "modeling", "virtual", "reality", "augmented", "cybernetics",
  "robotics", "automation", "artificial", "intelligence", "machine", "learning", "neural", "network", "nanotechnology", "biotechnology",
  "bioinformatics", "genomics", "proteomics", "cloning", "stem", "therapy", "pharmacology", "toxicology", "virology", "algorithm", "bandwidth", "binary", "blockchain", "browser", "byte", "cache", "chip", "cloud", "code",
  "compiler", "cpu", "cybersecurity", "database", "debug", "desktop", "domain", "encryption", "ethernet", "firewall",
  "framework", "gigabyte", "hardware", "host", "html", "internet", "java", "javascript", "kernel", "keyboard",
  "latency", "linux", "malware", "memory", "modem", "monitor", "motherboard", "network", "node", "password",
  "phishing", "pixel", "processor", "protocol", "python", "ram", "router", "server", "software", "syntax"
];

export const countries : string[] = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Costa Rica", "Croatia",
  "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon",
  "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
  "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
  "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman",
  "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar", "Republic of the Congo", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
  "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
  "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu",
  "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const food : string[] = [
  "apple", "banana", "broccoli", "burger", "cabbage", "carrot", "cheese", "cherry", "chocolate",
  "coconut", "coffee", "cookie", "cucumber", "donut", "garlic", "grape", "hamburger", "honey", "lemon",
  "lettuce", "mango", "melon", "mushroom", "noodle", "onion", "orange", "pancake", "papaya", "pasta",
  "peach", "peanut", "pepper", "pizza", "potato", "salad", "salmon", "sandwich", "sausage",
  "spinach", "strawberry", "sushi", "tomato", "vanilla", 'coleslaw', "walnut", "watermelon", "yogurt", 'shawarma', 'tigernut', 'ginger', 'soup', 'egg',  'pizza', 'rice', 'beans', 'millet', 'maize', 'popcorn', 'juice', 'meatpie', 'biscuit', 'fish', 'gizzard', 'beef'
];


export const geography : string[] = [
  // Continents & Subcontinents
  "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Oceania", 
  "Indian Subcontinent", "Arabian Peninsula", "Iberian Peninsula", "Scandinavia",

  // Oceans & Seas
  "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Arctic Ocean",
  "Mediterranean Sea", "Caribbean Sea", "Red Sea", "Black Sea", "Caspian Sea", 
  "Baltic Sea", "Arabian Sea", "Bering Sea", "North Sea", "Dead Sea", "Tasman Sea",

  // Major Rivers
  "Nile River", "Amazon River", "Yangtze River", "Mississippi River", "Ganges River", 
  "Thames River", "Danube River", "Rhine River", "Mekong River", "Volga River", 
  "Colorado River", "Indus River", "Congo River", "Zambezi River",

  // Mountains & Ranges
  "Mount Everest", "Mount Kilimanjaro", "Mount Fuji", "K2", "Denali", "Matterhorn", 
  "Mont Blanc", "Mount Elbrus", "Aconcagua", "Mount Vesuvius", "Mount Etna",
  "Himalayas", "Andes", "Alps", "Rocky Mountains", "Appalachians", "Ural Mountains", 
  "Atlas Mountains", "Pyrenees", "Caucasus Mountains",

  // Natural Landmarks & Biomes
  "Grand Canyon", "Great Barrier Reef", "Sahara Desert", "Gobi Desert", "Kalahari Desert", 
  "Mojave Desert", "Amazon Rainforest", "Niagara Falls", "Victoria Falls", "Angel Falls", 
  "Mariana Trench", "Galapagos Islands", "Madagascar", "Greenland",

  // Man-Made World Landmarks
  "Great Wall of China", "Pyramids of Giza", "Machu Picchu", "Taj Mahal", "Colosseum", 
  "Petra", "Stonehenge", "Eiffel Tower", "Statue of Liberty", "Acropolis", "Angkor Wat", 
  "Chichen Itza", "Burj Khalifa", "Mount Rushmore",

  // Space & Astronomy
  "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", 
  "Milky Way", "Andromeda Galaxy", "Solar System", "The Sun", "The Moon", "Asteroid Belt",

  // Rocks & Geology
  "Basalt", "Granite", "Limestone", "Marble", "Obsidian", "Quartz", "Sandstone", 
  "Pumice", "Slate", "Shale", "Conglomerate", "Diorite", "Schist",

  // Geographic Terms
  "Equator", "Prime Meridian", "Tropic of Cancer", "Tropic of Capricorn", "North Pole", 
  "South Pole", "Northern Hemisphere", "Southern Hemisphere", "Archipelago", "Peninsula", 
  "Fjord", "Glacier", "Tundra", "Savanna", "Estuary", "Isthmus", "Strait", "Plateau"
];





